name: CI/CD

on:
  push:
  release:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: make install-build
      - name: Build package
        run: make build
